### ISSUE TITLE
心疼群主

### ISSUE THREAD

**Issue by ctsyl** [changdaye/shadowsocks-web#1]
好好的SS就这么没了 心酸

**Comment by changdaye** [comment]
呃。。。。

**Comment by changdaye** [comment]
@ctsyl 以后如果有机会重开的话 在通知你把 不过也就是只能邮件通知了 因为我群都解散了，

**Comment by ctsyl** [comment]
很关键  急切的等待你的消息

2017年1月17日星期二，changdaye <notifications@github.com> 写道：

**Comment by changdaye** [comment]
@ctsyl 等吧，估计年后了，如果到时候不修改用户表结构的话  那你们以前的pro用户还可以继续用，如果修改的话 就要从新买了 可能 到时候再说把，

**Comment by ctsyl** [comment]
可以可以，这个消息很关键

2017年1月18日星期三，changdaye <notifications@github.com> 写道：

**Comment by changdaye** [comment]
@ctsyl 其实现在虽然网站关了 但是我后台服务开着呢 有几台节点是可以
![image](https://cloud.githubusercontent.com/assets/13974225/22090049/36409ec2-de2a-11e6-9a09-4b6ba7e31b62.png)

**Comment by changdaye** [comment]
@ctsyl 这几台节点是可以用，其他的节点有些还没找回来有些就是彻底丢了

**Comment by ctsyl** [comment]
是的，日本的节点没用了，但是美国的节点还可以使用，我也再用80和226的节点

2017年1月19日星期四，changdaye <notifications@github.com> 写道：

**Comment by changdaye** [comment]
@ctsyl  嗯，已经开始在优化了，快的话年前改完 慢的话年后改完，就是可能要从新注册了。

**Comment by ctsyl** [comment]
吸取上一次的教训，密码要复杂且不同，最好可以通过密码管理软件管理密码
，我因为你服务器密码被盗还特地下了个密码管理软件，心有戚戚啊
2017年1月19日星期四，changdaye <notifications@github.com> 写道：

**Comment by ctsyl** [comment]
进度如何

2017年1月19日星期四，池塘锁烟柳 <lmm794814694@gmail.com> 写道：

**Comment by changdaye** [comment]
@ctsyl http://www.ssplatform.xyz/code.php

**Comment by ctsyl** [comment]
没有QQ群吗  免费用户好像也可以使用PRO节点哦

2017年1月23日星期一，changdaye <notifications@github.com> 写道：

**Comment by ctsyl** [comment]
试了下 免费用户不能用 PRO才能用


2017-01-23 12:19 GMT+08:00 池塘锁烟柳 <lmm794814694@gmail.com>:

**Comment by changdaye** [comment]
@ctsyl 没有qq 群 懒得建了。 免费用户不能用pro 节点把  只有pro 用户才能用

**Comment by ctsyl** [comment]
qq群才有意思

2017年1月23日星期一，changdaye <notifications@github.com> 写道：

**Comment by ctsyl** [comment]
不考虑建个qq群吗？


2017年1月23日星期一，池塘锁烟柳 <lmm794814694@gmail.com> 写道：

**Comment by changdaye** [comment]
你创建个， 我直接挂上就行了 @ctsyl

**Comment by ctsyl** [comment]
.......可以我用我小号C个


2017年1月25日星期三，changdaye <notifications@github.com> 写道：

**Comment by ctsyl** [comment]
c是c好了，会不会不太安全最近好像在严查605844556，要c个电报群吗？

2017年1月25日星期三，池塘锁烟柳 <lmm794814694@gmail.com> 写道：

**Comment by changdaye** [comment]
QQ群490303524 @ctsyl

**Comment by changdaye** [comment]
这个把 我挂了机器人了 @ctsyl

**Comment by ctsyl** [comment]
怎么挂？

2017-01-25 18:19 GMT+08:00 changdaye <notifications@github.com>:

**Comment by ctsyl** [comment]
哦哦 看懂了 你C了啊

2017-01-25 18:52 GMT+08:00 池塘锁烟柳 <lmm794814694@gmail.com>:

**Comment by ctsyl** [comment]
需要宣传下吗？

2017年1月25日星期三，池塘锁烟柳 <lmm794814694@gmail.com> 写道：

**Comment by changdaye** [comment]
@ctsyl 随便啊  你有资源就宣传下被  我睡觉去了

**Comment by changdaye** [comment]
@ctsyl 已处理
